<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>Lucy.Console</AssemblyName>
    <RootNamespace>Lucy.Console</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <Company>Spokesoft</Company>
    <Authors>Spokesoft</Authors>
    <Description>Project management tool for the command line</Description>
    <PackAsTool>true</PackAsTool>
    <PackageId>Spokesoft.Lucy</PackageId>
    <PackageProjectUrl>https://spokesoft.github.io/lucy</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>tool cli dotnet agile scrum</PackageTags>
    <ToolCommandName>lucy</ToolCommandName>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/spokesoft/lucy.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.9" />
    <PackageReference Include="Spectre.Console" Version="0.51.1" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.51.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../CHANGELOG.md" Pack="true" PackagePath="/" />
    <None Include="../../icon.png" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE" Pack="true" PackagePath="/" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lucy.Console.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>