name: Build and publish

on:
  push:
    tags:
      - "v*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      CONSOLE_PROJECT: 'src/Console/Console.csproj'
      ARTIFACTS_DIR: './artifacts'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh

      - name: Update version numbers
        run: ./scripts/version.sh "${GITHUB_REF_NAME#v}"

      - name: Update changelog
        run: ./scripts/changelog.sh "${GITHUB_REF_NAME#v}"

      - name: Commit changelog
        env:
          REF_NAME: ${{ github.ref_name }}
          AUTHOR_NAME: ${{ github.actor }}
          AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          git config user.name "${AUTHOR_NAME}"
          git config user.email "${AUTHOR_EMAIL}"
          git add Directory.Build.props || true
          git add CHANGELOG.md || true

          if ! git diff --cached --quiet; then
            BRANCH="release/${{ github.ref_name }}"
            git checkout -B "$BRANCH"
            git commit -m "chore(release): Update for release ${REF_NAME} [skip ci]" || true
            git push --set-upstream origin "$BRANCH"
          else
            echo "No changes to commit"
            return 1
          fi

      - name: Restore solution dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Test solution
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack Tool
        run: dotnet pack "${CONSOLE_PROJECT}" --configuration Release --no-build --output "${ARTIFACTS_DIR}"

      - name: Publish package to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/Spokesoft.Lucy.*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json

      - name: Publish symbols to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/Spokesoft.Lucy.*.snupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json

      - name: Delete temporary release branch
        if: ${{ success() }}
        run: |
          set -euo pipefail
          BRANCH="release/${{ github.ref_name }}"
          git push origin --delete "$BRANCH" || echo "Remote branch '$BRANCH' not found or deletion failed"
        shell: bash