name: Release

on:
  push:
    branches:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Make script executable
        run: chmod +x ./scripts/build.sh

      - name: Run build script
        run: ./scripts/build.sh --test --release --output ./artifacts

      - name: Create Release Package
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      - name: Upload Release Package
        uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: ./artifacts
